# Examen

In [9]:
import pandas as pd
import numpy as np
from scipy import misc
import matplotlib.pyplot as plt

**1. Crear un vector de ceros de tamaño 10**

In [8]:
vector_ceros = np.zeros(10)

print(vector_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**2. Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1**

In [19]:
vector_ceros2 = np.zeros(10)
vector_ceros2[5] = 1

print(vector_ceros2)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


**3. Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc**

In [17]:
vector = np.random.rand(50)

vector_reordenado = vector[::1]

print(vector_reordenado)

[0.3777131  0.94730581 0.5177058  0.08833087 0.69300591 0.83453035
 0.45444394 0.04867044 0.39197011 0.49090171 0.85896425 0.77494315
 0.82167373 0.36583369 0.51441892 0.39243226 0.81501844 0.12418177
 0.27001727 0.95131034 0.00560132 0.71933375 0.65969153 0.27106267
 0.47088895 0.42365159 0.15546982 0.77682853 0.14097485 0.50161922
 0.89919163 0.1544059  0.97172011 0.32595621 0.38962521 0.13817763
 0.54607499 0.84941893 0.75620685 0.59785956 0.15269205 0.47589071
 0.7229342  0.6663195  0.6469582  0.08975246 0.46151116 0.50950065
 0.12871265 0.1107474 ]


**4. Crear una matriz de 3 x 3 con valores del cero al 8**

In [12]:
matriz = np.array(range(9))
matriz = matriz.reshape(3, 3)

print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**5. Encontrar los indices que no sean cero en un arreglo**

In [16]:
arreglo = np.array([1,2,0,0,4,0])

distinct_cero = np.where(arreglo != 0)

print(distinct_cero)


(array([0, 1, 4], dtype=int64),)


**6. Crear una matriz de identidad 3 x 3**

In [18]:
matriz_identidad = np.identity(3)

print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**7. Crear una matriz 3 x 3 x 3 con valores randomicos**

In [20]:
matriz_randomica = np.random.rand(3, 3, 3)

print(matriz_randomica)

[[[0.59803233 0.31044142 0.29982278]
  [0.14535448 0.65296632 0.53735923]
  [0.37295251 0.2053004  0.17019733]]

 [[0.48460089 0.71944321 0.15478064]
  [0.94324171 0.17806152 0.13361349]
  [0.62045342 0.89111702 0.88382506]]

 [[0.15596905 0.91523361 0.87754004]
  [0.1412457  0.54399833 0.00964579]
  [0.30245049 0.29471785 0.88322394]]]


**8. Crear una matriz 10 x 10 y encontrar el mayor y el menor**

In [21]:
matriz = np.random.rand(10, 10)

mayor = matriz.max()
menor = matriz.min()

print("La matriz es:", matriz)
print(f"\nSu elemento mayor es {mayor} y su elemento menor es {menor}")

La matriz es: [[0.44947225 0.13094999 0.46658039 0.3640052  0.0638934  0.57501015
  0.7502463  0.83995157 0.84865651 0.60069675]
 [0.19207388 0.30628641 0.63132323 0.62019821 0.46786939 0.48202575
  0.73175427 0.89933362 0.37678254 0.90085931]
 [0.27253105 0.72562227 0.05171082 0.57245493 0.37648692 0.17857707
  0.37068694 0.51718542 0.34244607 0.10516476]
 [0.73806441 0.70812961 0.70027046 0.99807549 0.6669832  0.43144679
  0.6680386  0.64992377 0.30263837 0.66537857]
 [0.35601971 0.50832213 0.89088035 0.10214051 0.93466879 0.47502432
  0.85417211 0.47720194 0.84244392 0.52620545]
 [0.93984581 0.67694859 0.96872392 0.63374188 0.11365865 0.53229559
  0.94330277 0.3503982  0.45517304 0.92049782]
 [0.42145273 0.6300339  0.25964343 0.00761057 0.36015536 0.02135891
  0.04906793 0.5270706  0.01502479 0.03547257]
 [0.95015909 0.43522422 0.32077327 0.88636798 0.02426764 0.41168157
  0.89009115 0.92032894 0.01754723 0.93662743]
 [0.75132327 0.06486054 0.27229225 0.91025432 0.80574913 0.3772880

**9. Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)**

**10. ¿Como crear una serie de una lista, diccionario o arreglo?**

In [22]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_lista = pd.Series(mylist)
serie_arreglo = pd.Series(myarr)
serie_diccionario = pd.Series(mydict)

print(f"Las series son:\nSerie de una lista:\n{serie_lista}\nSerie de un arreglo:\n{serie_arreglo}\nSerie de un diccionario:\n{serie_diccionario}")


Las series son:
Serie de una lista:
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
Serie de un arreglo:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
Serie de un diccionario:
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


**11. ¿Como convertir el indice de una serie en una columna de un DataFrame?**

In [23]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice

df_serie = pd.DataFrame(ser)

print(df_serie)

    0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25


**12. ¿Como combinar varias series para hacer un DataFrame?**

In [24]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df_combinado = pd.DataFrame({'ser1': ser1, 'ser2': ser2})

print(df_combinado)

   ser1  ser2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25


**13. ¿Como obtener los items que esten en una serie A y no en una serie B?**

In [26]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items = ser1[~ser1.isin(ser2)]

print(f"los items de la seria 1 que no estan en la serie 2 son:\n{items}")

los items de la seria 1 que no estan en la serie 2 son:
0    1
1    2
2    3
dtype: int64


**14. ¿Como obtener los items que no son comunes en una serie A y serie B?**

In [27]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_no_comunes_A = ser1[~ser1.isin(ser2)]
items_no_comunes_B = ser2[~ser2.isin(ser1)]
items_no_comunes = pd.concat([items_no_comunes_A, items_no_comunes_B])

print(f"Los items que no se repiten en ambas series son:\n{items_no_comunes}")

Los items que no se repiten en ambas series son:
0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


**15. ¿Como obtener el numero de veces que se repite un valor en una serie?**

In [30]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

veces_repetido = ser.value_counts()

print(f"Los elementos se repiten de la siguiente manera:\n{veces_repetido}")

Los elementos se repiten de la siguiente manera:
e    6
g    5
h    5
c    4
f    4
d    3
a    2
b    1
dtype: int64


**16. ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?**

In [38]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

valores_repetidos = ser.value_counts()
valores_repetidos[2:] = 0

print(valores_repetidos)

3    5
4    3
2    0
1    0
dtype: int64


**17. ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?**

In [40]:
ser = pd.Series(np.random.randint(1, 10, 35))

df_ser = pd.DataFrame(ser.values.reshape(7, 5))

print(f"Dataframe:\n{df_ser}")

Dataframe:
   0  1  2  3  4
0  9  1  3  9  3
1  5  8  1  1  2
2  5  1  7  1  9
3  6  8  5  2  9
4  6  1  5  4  9
5  2  5  6  8  3
6  4  6  4  9  8


**18. ¿Obtener los valores de una serie conociendo la posicion por indice?**

In [37]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

print(ser[pos])

0     a
4     e
8     i
14    o
20    u
dtype: object


**19. ¿Como anadir series vertical u horizontalmente a un DataFrame?**

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

**20. ¿Obtener la media de una serie agrupada por otra serie?**

In [ ]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

**21. ¿Como importar solo columnas especificas de un archivo csv?**

In [36]:
path = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

archivo = pd.read_csv(path, usecols=['age', 'crim'])

print(f"Los registros 'age' y 'crim' son:\n{archivo}")
    

Los registros 'age' y 'crim' son:
        crim   age
0    0.00632  65.2
1    0.02731  78.9
2    0.02729  61.1
3    0.03237  45.8
4    0.06905  54.2
..       ...   ...
501  0.06263  69.1
502  0.04527  76.7
503  0.06076  91.0
504  0.10959  89.3
505  0.04741  80.8

[506 rows x 2 columns]
