# Carrera Alvarez Alex Francisco 

## Crea un Dataframe de 10 registros y 6 columnas y consigue las 5 primeros y los 5 ultimos registros

In [9]:
import pandas as pd
data = pd.DataFrame(columns=('order', 'family', 'num', 'sequence', 'genero', 'edad'))

data.loc[len(data)]=['Tymovirales','Alphaflexiviridae',1,'AACGTTAAUGGUGAA', 'male',8]
data.loc[len(data)]=['Tymovirales','Alphaflexideridae',1,'AACGTTAAUGGUGAA', 'female',7]
data.loc[len(data)]=['Tymovirales','Alphaflexidiridae',1,'AACGTTAAUGGUGAA', 'male',9]
data.loc[len(data)]=['Tymovirales','Alphaflexidoridae',1,'AACGTTAAUGGUGAA', 'female',10]
data.loc[len(data)]=['Tymovirales','Alphaflexiriridae',1,'AACGTTAAUGGUGAA', 'male',6]
data.loc[len(data)]=['Tymovirales','Alphaflexieiridae',1,'AACGTTAAUGGUGAA', 'female',5]
data.loc[len(data)]=['Tymovirales','Alphaflexigiridae',1,'AACGTTAAUGGUGAA', 'male',11]
data.loc[len(data)]=['Tymovirales','Alphaflexihiridae',1,'AACGTTAAUGGUGAA', 'female',27]
data.loc[len(data)]=['Tymovirales','Alphaflexiijridae',1,'AACGTTAAUGGUGAA', 'male',84]
data.loc[len(data)]=['Tymovirales','Alphaflexijiridae',1,'AACGTTAAUGGUGAA', 'female',12]

print(data)

         order             family num         sequence  genero edad
0  Tymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
1  Tymovirales  Alphaflexideridae   1  AACGTTAAUGGUGAA  female    7
2  Tymovirales  Alphaflexidiridae   1  AACGTTAAUGGUGAA    male    9
3  Tymovirales  Alphaflexidoridae   1  AACGTTAAUGGUGAA  female   10
4  Tymovirales  Alphaflexiriridae   1  AACGTTAAUGGUGAA    male    6
5  Tymovirales  Alphaflexieiridae   1  AACGTTAAUGGUGAA  female    5
6  Tymovirales  Alphaflexigiridae   1  AACGTTAAUGGUGAA    male   11
7  Tymovirales  Alphaflexihiridae   1  AACGTTAAUGGUGAA  female   27
8  Tymovirales  Alphaflexiijridae   1  AACGTTAAUGGUGAA    male   84
9  Tymovirales  Alphaflexijiridae   1  AACGTTAAUGGUGAA  female   12


In [10]:
print(data[:5])

         order             family num         sequence  genero edad
0  Tymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
1  Tymovirales  Alphaflexideridae   1  AACGTTAAUGGUGAA  female    7
2  Tymovirales  Alphaflexidiridae   1  AACGTTAAUGGUGAA    male    9
3  Tymovirales  Alphaflexidoridae   1  AACGTTAAUGGUGAA  female   10
4  Tymovirales  Alphaflexiriridae   1  AACGTTAAUGGUGAA    male    6


In [14]:
print(data[5:10])

         order             family num         sequence  genero edad
5  Tymovirales  Alphaflexieiridae   1  AACGTTAAUGGUGAA  female    5
6  Tymovirales  Alphaflexigiridae   1  AACGTTAAUGGUGAA    male   11
7  Tymovirales  Alphaflexihiridae   1  AACGTTAAUGGUGAA  female   27
8  Tymovirales  Alphaflexiijridae   1  AACGTTAAUGGUGAA    male   84
9  Tymovirales  Alphaflexijiridae   1  AACGTTAAUGGUGAA  female   12


## Crear un dataframe pasando un arreglo de numpy de 6 x 4 con una fecha como indice y con columnas A, B, C, D randomico

In [29]:
import numpy as np

e = np.random.rand(6,4)
print(e)


[[0.56109763 0.97926174 0.57845888 0.82986473]
 [0.87689043 0.43164968 0.36521649 0.46507098]
 [0.8780603  0.56002658 0.76274161 0.05025334]
 [0.45151385 0.33668466 0.84315982 0.33499561]
 [0.97003651 0.09410074 0.93299817 0.72202388]
 [0.17727404 0.46104226 0.77497382 0.99147932]]


In [69]:

e_dataframe = pd.DataFrame(e)
e_dataframe.rename(index=str, columns={0:'A', 1:'B',2:'C',3:'D'})


A  B   C  D  4   5
0   5  5  10  2  1   8
1   7  2  10  6  7   8
2   5  3   4  7  3  10
3   3  5   9  7  6   3
4  10  3   8  6  7   8
5   8  3   5  2  3   3
6   1  3   3  2  4   2
7   1  8   1  8  9  10
8   6  4   2  9  7   9
9   5  7  10  4  2   1

## Crear un Dataframe con 10 registros y 6 columnas y con una propiedad del Dataframe mostrar las columnas, con otro comando mostrar los valores

In [31]:
data = pd.DataFrame(columns=('order', 'family', 'num', 'sequence', 'genero', 'edad'))

data.loc[len(data)]=['Tymovirales','Alphaflexiviridae',1,'AACGTTAAUGGUGAA', 'male',8]
data.loc[len(data)]=['Tymovirales','Alphaflexideridae',1,'AACGTTAAUGGUGAA', 'female',7]
data.loc[len(data)]=['Tymovirales','Alphaflexidiridae',1,'AACGTTAAUGGUGAA', 'male',9]
data.loc[len(data)]=['Tymovirales','Alphaflexidoridae',1,'AACGTTAAUGGUGAA', 'female',10]
data.loc[len(data)]=['Tymovirales','Alphaflexiriridae',1,'AACGTTAAUGGUGAA', 'male',6]
data.loc[len(data)]=['Tymovirales','Alphaflexieiridae',1,'AACGTTAAUGGUGAA', 'female',5]
data.loc[len(data)]=['Tymovirales','Alphaflexigiridae',1,'AACGTTAAUGGUGAA', 'male',11]
data.loc[len(data)]=['Tymovirales','Alphaflexihiridae',1,'AACGTTAAUGGUGAA', 'female',27]
data.loc[len(data)]=['Tymovirales','Alphaflexiijridae',1,'AACGTTAAUGGUGAA', 'male',84]
data.loc[len(data)]=['Tymovirales','Alphaflexijiridae',1,'AACGTTAAUGGUGAA', 'female',12]

print(data)

         order             family num         sequence  genero edad
0  Tymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
1  Tymovirales  Alphaflexideridae   1  AACGTTAAUGGUGAA  female    7
2  Tymovirales  Alphaflexidiridae   1  AACGTTAAUGGUGAA    male    9
3  Tymovirales  Alphaflexidoridae   1  AACGTTAAUGGUGAA  female   10
4  Tymovirales  Alphaflexiriridae   1  AACGTTAAUGGUGAA    male    6
5  Tymovirales  Alphaflexieiridae   1  AACGTTAAUGGUGAA  female    5
6  Tymovirales  Alphaflexigiridae   1  AACGTTAAUGGUGAA    male   11
7  Tymovirales  Alphaflexihiridae   1  AACGTTAAUGGUGAA  female   27
8  Tymovirales  Alphaflexiijridae   1  AACGTTAAUGGUGAA    male   84
9  Tymovirales  Alphaflexijiridae   1  AACGTTAAUGGUGAA  female   12


In [33]:
print(data.columns.values)

['order' 'family' 'num' 'sequence' 'genero' 'edad']


In [35]:
print(data.values)

[['Tymovirales' 'Alphaflexiviridae' 1 'AACGTTAAUGGUGAA' 'male' 8]
 ['Tymovirales' 'Alphaflexideridae' 1 'AACGTTAAUGGUGAA' 'female' 7]
 ['Tymovirales' 'Alphaflexidiridae' 1 'AACGTTAAUGGUGAA' 'male' 9]
 ['Tymovirales' 'Alphaflexidoridae' 1 'AACGTTAAUGGUGAA' 'female' 10]
 ['Tymovirales' 'Alphaflexiriridae' 1 'AACGTTAAUGGUGAA' 'male' 6]
 ['Tymovirales' 'Alphaflexieiridae' 1 'AACGTTAAUGGUGAA' 'female' 5]
 ['Tymovirales' 'Alphaflexigiridae' 1 'AACGTTAAUGGUGAA' 'male' 11]
 ['Tymovirales' 'Alphaflexihiridae' 1 'AACGTTAAUGGUGAA' 'female' 27]
 ['Tymovirales' 'Alphaflexiijridae' 1 'AACGTTAAUGGUGAA' 'male' 84]
 ['Tymovirales' 'Alphaflexijiridae' 1 'AACGTTAAUGGUGAA' 'female' 12]]


##  Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe describir estadisticamente el Dataframe

In [36]:
e = np.random.rand(6,10)
e_dataframe = pd.DataFrame(e)

In [37]:
e_dataframe.describe()

0         1         2         3         4         5         6  \
count  6.000000  6.000000  6.000000  6.000000  6.000000  6.000000  6.000000   
mean   0.519559  0.471424  0.707505  0.436201  0.294362  0.494435  0.792916   
std    0.346536  0.313188  0.243140  0.144310  0.225215  0.156011  0.160007   
min    0.166943  0.062629  0.312069  0.345172  0.079878  0.298053  0.495310   
25%    0.216101  0.277492  0.598961  0.366125  0.107948  0.363563  0.783466   
50%    0.515499  0.428460  0.754668  0.382369  0.234399  0.524430  0.825706   
75%    0.732601  0.710781  0.847853  0.410672  0.470879  0.605646  0.864423   
max    0.998143  0.876938  0.997650  0.726478  0.601995  0.677039  0.964055   

              7         8         9  
count  6.000000  6.000000  6.000000  
mean   0.609431  0.540149  0.575781  
std    0.350566  0.241968  0.314750  
min    0.020487  0.293104  0.280089  
25%    0.482672  0.336414  0.301081  
50%    0.655391  0.499282  0.510734  
75%    0.846693  0.725717  0.824907  
max    0.989759  0.865905  0.992303

## Crear un Dataframe con 10 registros y 6 columnas y con una funcion del Dataframe transponer los datos

In [38]:
e_dataframe.transpose()

0         1         2         3         4         5
0  0.166943  0.998143  0.728333  0.302665  0.187246  0.734024
1  0.493733  0.248927  0.363188  0.062629  0.876938  0.783130
2  0.684044  0.997650  0.570600  0.312069  0.825292  0.855373
3  0.363346  0.390277  0.374460  0.345172  0.726478  0.417470
4  0.601995  0.311411  0.157387  0.091468  0.079878  0.524035
5  0.677039  0.615229  0.327430  0.298053  0.471963  0.576898
6  0.964055  0.862098  0.781517  0.865199  0.789315  0.495310
7  0.868963  0.989759  0.530899  0.466597  0.779883  0.020487
8  0.782326  0.865905  0.555890  0.293104  0.442673  0.300994
9  0.352335  0.876832  0.280089  0.992303  0.283997  0.669132

## Crear un Dataframe con 10 registros y 6 columnas y Ordenar el dataframe 1 vez por cada columna, ascendente y descendente

In [44]:
data = pd.DataFrame(columns=('order', 'family', 'num', 'sequence', 'genero', 'edad'))

data.loc[len(data)]=['Aymovirales','Alphaflexiviridae',1,'AACGTTAAUGGUGAA', 'male',8]
data.loc[len(data)]=['Cymovirales','Alphaflexideridae',2,'AACGTTAAUGGUGAA', 'female',7]
data.loc[len(data)]=['Bymovirales','Alphaflexidiridae',5,'AACGTTAAUGGUGAA', 'male',9]
data.loc[len(data)]=['Dymovirales','Alphaflexidoridae',6,'AACGTTAAUGGUGAA', 'female',10]
data.loc[len(data)]=['Rymovirales','Alphaflexiriridae',7,'AACGTTAAUGGUGAA', 'male',6]
data.loc[len(data)]=['Eymovirales','Alphaflexieiridae',8,'AACGTTAAUGGUGAA', 'female',5]
data.loc[len(data)]=['Gymovirales','Alphaflexigiridae',9,'AACGTTAAUGGUGAA', 'male',11]
data.loc[len(data)]=['Symovirales','Alphaflexihiridae',0,'AACGTTAAUGGUGAA', 'female',27]
data.loc[len(data)]=['Oymovirales','Alphaflexiijridae',12,'AACGTTAAUGGUGAA', 'male',84]
data.loc[len(data)]=['Mymovirales','Alphaflexijiridae',6,'AACGTTAAUGGUGAA', 'female',12]

by_year = data.sort_values('order')
by_year.head(10)

order             family num         sequence  genero edad
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27

In [53]:
by_family = data.sort_values('family', ascending=False)
by_family.head(10)

order             family num         sequence  genero edad
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7

In [52]:
by_family = data.sort_values('family', ascending=True)
by_family.head(10)

order             family num         sequence  genero edad
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8

In [55]:
by_num = data.sort_values('num', ascending=True)
by_num.head(10)

order             family num         sequence  genero edad
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84

In [56]:
by_num = data.sort_values('num', ascending=False)
by_num.head(10)

order             family num         sequence  genero edad
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27

In [57]:
by_sequence = data.sort_values('sequence',ascending=False)
#by_sequence = data.sort_values('sequence'ascending=True)
by_sequence.head(10)

order             family num         sequence  genero edad
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12

In [47]:
by_genero = data.sort_values('genero',ascending=False)
#by_genero = data.sort_values('genero',ascending=True)
by_genero.head(10)

order             family num         sequence  genero edad
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84

In [48]:
by_edad = data.sort_values('edad',ascending=False)
by_edad = data.sort_values('edad',ascending=True)
by_edad.head(10)

order             family num         sequence  genero edad
5  Eymovirales  Alphaflexieiridae   8  AACGTTAAUGGUGAA  female    5
4  Rymovirales  Alphaflexiriridae   7  AACGTTAAUGGUGAA    male    6
1  Cymovirales  Alphaflexideridae   2  AACGTTAAUGGUGAA  female    7
0  Aymovirales  Alphaflexiviridae   1  AACGTTAAUGGUGAA    male    8
2  Bymovirales  Alphaflexidiridae   5  AACGTTAAUGGUGAA    male    9
3  Dymovirales  Alphaflexidoridae   6  AACGTTAAUGGUGAA  female   10
6  Gymovirales  Alphaflexigiridae   9  AACGTTAAUGGUGAA    male   11
9  Mymovirales  Alphaflexijiridae   6  AACGTTAAUGGUGAA  female   12
7  Symovirales  Alphaflexihiridae   0  AACGTTAAUGGUGAA  female   27
8  Oymovirales  Alphaflexiijridae  12  AACGTTAAUGGUGAA    male   84

## Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y seleccionar en un nuevo Dataframe solo los valores mayores a 7

In [65]:
e = np.random.randint(1,11, size=(10, 6))
e_dataframe = pd.DataFrame(e)
print(e_dataframe)



    0  1   2  3  4   5
0   5  5  10  2  1   8
1   7  2  10  6  7   8
2   5  3   4  7  3  10
3   3  5   9  7  6   3
4  10  3   8  6  7   8
5   8  3   5  2  3   3
6   1  3   3  2  4   2
7   1  8   1  8  9  10
8   6  4   2  9  7   9
9   5  7  10  4  2   1


In [70]:
data_filter = e_dataframe.values > 7

In [71]:
print(data_filter)

[[False False  True False False  True]
 [False False  True False False  True]
 [False False False False False  True]
 [False False  True False False False]
 [ True False  True False False  True]
 [ True False False False False False]
 [False False False False False False]
 [False  True False  True  True  True]
 [False False False  True False  True]
 [False False  True False False False]]


## Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 o valores NaN. Luego llenar los valores NaN con 0

In [74]:
import pandas as pd
import numpy as np

dummyarray = np.empty((10,6))
dummyarray[:] = np.nan

df = pd.DataFrame(dummyarray)
print(df)

    0   1   2   3   4   5
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN
5 NaN NaN NaN NaN NaN NaN
6 NaN NaN NaN NaN NaN NaN
7 NaN NaN NaN NaN NaN NaN
8 NaN NaN NaN NaN NaN NaN
9 NaN NaN NaN NaN NaN NaN


In [79]:
df_bool = pd.isnull(df)
print(df_bool)

      0     1     2     3     4     5
0  True  True  True  True  True  True
1  True  True  True  True  True  True
2  True  True  True  True  True  True
3  True  True  True  True  True  True
4  True  True  True  True  True  True
5  True  True  True  True  True  True
6  True  True  True  True  True  True
7  True  True  True  True  True  True
8  True  True  True  True  True  True
9  True  True  True  True  True  True


In [85]:
df_sin_nan = df.dropna(how='any')
print(df_sin_nan)

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5]
Index: []


## Crear un Dataframe con 10 registros y 6 columnas llenas de números randomicos del 1 al 10 y sacar la media, la mediana, el promedio

In [86]:
e = np.random.randint(1,11, size=(10, 6))
e_dataframe = pd.DataFrame(e)
print(e_dataframe)

   0   1   2   3   4   5
0  7   4   4   8   4   8
1  8   3   2   1   3  10
2  3   5   5   5   6   6
3  6   7   6   5   3   6
4  3  10   9   7   2  10
5  9   2   3   3  10   2
6  1   8   7   5   4   8
7  6   3  10  10  10   4
8  2   7   5   5  10   2
9  5   4  10   3   7   6


In [88]:
media = e_dataframe.mean()
print(media)

0    5.0
1    5.3
2    6.1
3    5.2
4    5.9
5    6.2
dtype: float64


In [89]:
mediana = e_dataframe.median()
print(mediana)

0    5.5
1    4.5
2    5.5
3    5.0
4    5.0
5    6.0
dtype: float64


In [90]:
promedio = e_dataframe.mode()
print(promedio)

     0  1     2    3     4    5
0  3.0  3   5.0  5.0  10.0  6.0
1  6.0  4  10.0  NaN   NaN  NaN
2  NaN  7   NaN  NaN   NaN  NaN
